using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Media.Imaging;
using KetabaPOS.Desktop.Core.Interfaces;
using KetabaPOS.Desktop.Core.Models;
using KetabaPOS.Desktop.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using WpfMedia = System.Windows.Media;
using WpfControls = System.Windows.Controls;
using WpfSize = System.Windows.Size;
using WpfHA = System.Windows.HorizontalAlignment;
using WpfVA = System.Windows.VerticalAlignment;

namespace KetabaPOS.Desktop.Infrastructure.Services;

public class ReceiptService : IReceiptService
{
    private readonly AppDbContext _context;
    private Dictionary<string, string> _settings = new();

    private static readonly WpfMedia.Color PrimaryBlue = WpfMedia.Color.FromRgb(37, 99, 235);
    private static readonly WpfMedia.Color LightGrayBg = WpfMedia.Color.FromRgb(248, 250, 252);
    private static readonly WpfMedia.Color BorderGray = WpfMedia.Color.FromRgb(226, 232, 240);
    private static readonly WpfMedia.Color DarkText = WpfMedia.Color.FromRgb(30, 41, 59);
    private static readonly WpfMedia.Color MutedText = WpfMedia.Color.FromRgb(100, 116, 139);

    public ReceiptService(AppDbContext context) { _context = context; }

    public async Task<Sale?> GetSaleWithDetailsAsync(int saleId)
    {
        return await _context.Sales
            .Include(s => s.User)
            .Include(s => s.Customer)
            .Include(s => s.SaleItems).ThenInclude(si => si.Product)
            .FirstOrDefaultAsync(s => s.Id == saleId);
    }

    private async Task LoadSettingsAsync()
    {
        _settings = await _context.Settings.ToDictionaryAsync(s => s.Key, s => s.Value);
    }

    private string Setting(string key, string fallback = "") =>
        _settings.GetValueOrDefault(key, fallback);

    public async Task<FixedDocument> BuildReceiptDocumentAsync(Sale sale)
    {
        await LoadSettingsAsync();

        var doc = new FixedDocument();
        var pageContent = new PageContent();
        var fixedPage = new FixedPage { Width = 794, Height = 1123 };
        pageContent.Child = fixedPage;
        doc.Pages.Add(pageContent);

        var stack = new StackPanel
        {
            Margin = new Thickness(0, 24, 0, 24),
            Background = new WpfMedia.SolidColorBrush(WpfMedia.Colors.White)
        };
        fixedPage.Children.Add(stack);

        stack.Children.Add(CreateHeaderBorder(sale));

        stack.Children.Add(new TextBlock
        {
            Text = "RECEIPT / INVOICE",
            FontSize = 24, FontWeight = FontWeights.Bold,
            Foreground = new WpfMedia.SolidColorBrush(DarkText),
            TextAlignment = TextAlignment.Center,
            Margin = new Thickness(40, 20, 40, 4)
        });

        stack.Children.Add(CreateDivider(40));

        stack.Children.Add(CreateInfoSection(sale));

        stack.Children.Add(CreateDivider(20));

        stack.Children.Add(CreateTableSection(sale));

        stack.Children.Add(CreateDivider(20));

        stack.Children.Add(CreateTotalsSection(sale));

        stack.Children.Add(CreateDivider(16));

        var footer = Setting("receipt_footer", "Thank you for your purchase!");
        stack.Children.Add(new TextBlock
        {
            Text = footer,
            FontSize = 14,
            Foreground = new WpfMedia.SolidColorBrush(MutedText),
            TextAlignment = TextAlignment.Center,
            FontStyle = FontStyles.Italic,
            Margin = new Thickness(40, 12, 40, 0)
        });

        stack.Children.Add(new TextBlock
        {
            Text = $"Generated by Ketaba POS | {DateTime.Now:yyyy-MM-dd HH:mm}",
            FontSize = 10,
            Foreground = new WpfMedia.SolidColorBrush(MutedText),
            TextAlignment = TextAlignment.Center,
            Margin = new Thickness(40, 20, 40, 0)
        });

        return doc;
    }

    public async Task ExportToPdfAsync(Sale sale, string filePath)
    {
        await LoadSettingsAsync();
        QuestPDF.Settings.License = LicenseType.Community;

        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(11).FontFamily("Arial"));

                page.Header().Element(c => ComposePdfHeader(c, sale));
                page.Content().Element(c => ComposePdfContent(c, sale));
                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Generated by Ketaba POS | ").FontSize(9).FontColor(Colors.Grey.Medium);
                    t.Span($"{DateTime.Now:yyyy-MM-dd HH:mm}").FontSize(9).FontColor(Colors.Grey.Medium);
                });
            });
        }).GeneratePdf(filePath);
    }

    public async Task PrintReceiptAsync(Sale sale, bool showDialog = true)
    {
        var doc = await BuildReceiptDocumentAsync(sale);
        var dlg = new PrintDialog();
        if (showDialog)
        {
            if (dlg.ShowDialog() != true) return;
        }
        dlg.PrintDocument(doc.DocumentPaginator, $"Receipt-{sale.InvoiceNumber}");
    }

    // ========== WPF layout helpers using auto-stacking StackPanel ==========

    private Border CreateHeaderBorder(Sale sale)
    {
        var inner = new WpfControls.Grid();
        inner.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(80) });
        inner.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });

        var logoPath = Setting("company_logo");
        if (!string.IsNullOrEmpty(logoPath) && File.Exists(logoPath))
        {
            try
            {
                var img = new WpfControls.Image
                {
                    Source = new BitmapImage(new Uri(logoPath)),
                    Width = 64, Height = 64,
                    Stretch = WpfMedia.Stretch.Uniform
                };
                Grid.SetColumn(img, 0);
                inner.Children.Add(img);
            }
            catch { }
        }

        var infoStack = new StackPanel { Margin = new Thickness(16, 0, 0, 0) };
        Grid.SetColumn(infoStack, 1);
        infoStack.Children.Add(new TextBlock
        {
            Text = Setting("company_name", "KETABA POS"),
            FontSize = 22, FontWeight = FontWeights.Bold,
            Foreground = WpfMedia.Brushes.White
        });
        var addr = Setting("company_address");
        if (!string.IsNullOrEmpty(addr))
            infoStack.Children.Add(new TextBlock
            { Text = addr, FontSize = 12, Foreground = new WpfMedia.SolidColorBrush(WpfMedia.Color.FromRgb(191, 219, 254)) });
        var phone = Setting("company_phone");
        if (!string.IsNullOrEmpty(phone))
            infoStack.Children.Add(new TextBlock
            { Text = phone, FontSize = 12, Foreground = new WpfMedia.SolidColorBrush(WpfMedia.Color.FromRgb(191, 219, 254)) });
        inner.Children.Add(infoStack);

        return new Border
        {
            Background = new WpfMedia.SolidColorBrush(PrimaryBlue),
            Padding = new Thickness(40, 24, 40, 24),
            Child = inner
        };
    }

    private Border CreateDivider(double margin)
    {
        return new Border
        {
            Height = 1,
            Background = new WpfMedia.SolidColorBrush(BorderGray),
            Margin = new Thickness(40, margin, 40, margin)
        };
    }

    private WpfControls.Grid CreateInfoSection(Sale sale)
    {
        var grid = new WpfControls.Grid { Margin = new Thickness(40, 0, 40, 0) };
        grid.ColumnDefinitions.Add(new ColumnDefinition());
        grid.ColumnDefinitions.Add(new ColumnDefinition());
        for (int i = 0; i < 3; i++)
            grid.RowDefinitions.Add(new RowDefinition { Height = GridLength.Auto });

        AddInfoCell(grid, 0, 0, "Invoice #:", sale.InvoiceNumber);
        AddInfoCell(grid, 0, 1, "Date:", sale.CreatedAt.ToString("yyyy-MM-dd HH:mm"));
        AddInfoCell(grid, 0, 2, "Cashier:", sale.User?.DisplayName ?? "N/A");
        AddInfoCell(grid, 1, 0, "Payment:", sale.PaymentMethod.ToString());
        AddInfoCell(grid, 1, 1, "Customer:", sale.Customer?.Name ?? "Walk-in");
        AddInfoCell(grid, 1, 2, "Status:", sale.Status.ToString());
        return grid;
    }

    private static void AddInfoCell(WpfControls.Grid grid, int col, int row, string label, string value)
    {
        var panel = new StackPanel { Orientation = Orientation.Horizontal, Margin = new Thickness(0, 2, 0, 2) };
        panel.Children.Add(new TextBlock
        {
            Text = label, FontSize = 11, FontWeight = FontWeights.SemiBold,
            Foreground = new WpfMedia.SolidColorBrush(MutedText)
        });
        panel.Children.Add(new TextBlock
        {
            Text = " " + value, FontSize = 11,
            Foreground = new WpfMedia.SolidColorBrush(DarkText)
        });
        Grid.SetColumn(panel, col);
        Grid.SetRow(panel, row);
        grid.Children.Add(panel);
    }

    private StackPanel CreateTableSection(Sale sale)
    {
        var outer = new StackPanel { Margin = new Thickness(40, 0, 40, 0) };

        var headerGrid = new WpfControls.Grid { Background = new WpfMedia.SolidColorBrush(PrimaryBlue) };
        headerGrid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
        headerGrid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(56) });
        headerGrid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(90) });
        headerGrid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(80) });
        headerGrid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(90) });

        string[] headers = ["Item", "Qty", "Price", "Disc.", "Total"];
        for (int i = 0; i < headers.Length; i++)
        {
            var align = i == 0 ? TextAlignment.Left : TextAlignment.Right;
            var tb = new TextBlock
            {
                Text = headers[i], FontSize = 11, FontWeight = FontWeights.Bold,
                Foreground = WpfMedia.Brushes.White,
                TextAlignment = align, Padding = new Thickness(i > 0 ? 6 : 0, 6, 6, 6)
            };
            Grid.SetColumn(tb, i);
            headerGrid.Children.Add(tb);
        }
        outer.Children.Add(headerGrid);

        if (sale.SaleItems.Count == 0)
        {
            outer.Children.Add(new TextBlock
            {
                Text = "No items",
                FontSize = 11, Foreground = new WpfMedia.SolidColorBrush(MutedText),
                Padding = new Thickness(0, 8, 0, 8), TextAlignment = TextAlignment.Center
            });
            return outer;
        }

        bool alternate = false;
        foreach (var item in sale.SaleItems)
        {
            var rowGrid = new WpfControls.Grid();
            rowGrid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
            rowGrid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(56) });
            rowGrid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(90) });
            rowGrid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(80) });
            rowGrid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(90) });

            if (alternate)
                rowGrid.Background = new WpfMedia.SolidColorBrush(LightGrayBg);
            alternate = !alternate;

            string[] values = [
                item.Product?.Name ?? "Item",
                item.Quantity.ToString(),
                item.UnitPrice.ToString("N2"),
                item.DiscountAmount > 0 ? item.DiscountAmount.ToString("N2") : "-",
                item.TotalPrice.ToString("N2")
            ];

            for (int i = 0; i < values.Length; i++)
            {
                var align = i == 0 ? TextAlignment.Left : TextAlignment.Right;
                var tb = new TextBlock
                {
                    Text = values[i], FontSize = 11,
                    Foreground = new WpfMedia.SolidColorBrush(DarkText),
                    TextAlignment = align,
                    Padding = new Thickness(i > 0 ? 6 : 0, 4, 6, 4)
                };
                if (i == values.Length - 1)
                    tb.FontWeight = FontWeights.SemiBold;
                Grid.SetColumn(tb, i);
                rowGrid.Children.Add(tb);
            }

            rowGrid.Children.Add(new Border
            {
                Height = 0.5,
                Background = new WpfMedia.SolidColorBrush(BorderGray),
                VerticalAlignment = WpfVA.Bottom
            });

            outer.Children.Add(rowGrid);
        }

        return outer;
    }

    private StackPanel CreateTotalsSection(Sale sale)
    {
        var outer = new StackPanel { Margin = new Thickness(40, 0, 40, 0) };

        var alignGrid = new WpfControls.Grid();
        alignGrid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
        alignGrid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(220) });
        var panel = new StackPanel();
        Grid.SetColumn(panel, 1);
        alignGrid.Children.Add(panel);

        AddTotalRow(panel, "Subtotal:", sale.Subtotal, false);
        AddTotalRow(panel, "Tax:", sale.TaxAmount, false);
        if (sale.DiscountAmount > 0)
            AddTotalRow(panel, "Discount:", -sale.DiscountAmount, false);

        panel.Children.Add(new Border
        {
            Height = 1,
            Background = new WpfMedia.SolidColorBrush(BorderGray),
            Margin = new Thickness(0, 4, 0, 4)
        });

        AddTotalRow(panel, "TOTAL:", sale.TotalAmount, true);
        AddTotalRow(panel, "Paid:", sale.PaidAmount, false);
        AddTotalRow(panel, "Change:", sale.ChangeAmount, false);

        outer.Children.Add(alignGrid);
        return outer;
    }

    private static void AddTotalRow(StackPanel parent, string label, decimal value, bool bold)
    {
        var grid = new WpfControls.Grid();
        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(1, GridUnitType.Star) });
        grid.ColumnDefinitions.Add(new ColumnDefinition { Width = new GridLength(100) });

        var lbl = new TextBlock
        {
            Text = label,
            FontSize = bold ? 16 : 12,
            FontWeight = bold ? FontWeights.Bold : FontWeights.Medium,
            Foreground = new WpfMedia.SolidColorBrush(bold ? PrimaryBlue : DarkText),
            HorizontalAlignment = WpfHA.Right,
            Margin = new Thickness(0, 2, 0, 2)
        };
        Grid.SetColumn(lbl, 0);
        grid.Children.Add(lbl);

        var val = new TextBlock
        {
            Text = value.ToString("N2"),
            FontSize = bold ? 16 : 12,
            FontWeight = bold ? FontWeights.Bold : FontWeights.Medium,
            Foreground = new WpfMedia.SolidColorBrush(bold ? PrimaryBlue : DarkText),
            TextAlignment = TextAlignment.Right,
            Margin = new Thickness(8, 2, 0, 2)
        };
        Grid.SetColumn(val, 1);
        grid.Children.Add(val);

        parent.Children.Add(grid);
    }

    // ========== PDF helpers (QuestPDF — already correct) ==========

    private void ComposePdfHeader(IContainer container, Sale sale)
    {
        container.Column(col =>
        {
            col.Item().Row(row =>
            {
                var logoPath = Setting("company_logo");
                if (!string.IsNullOrEmpty(logoPath) && File.Exists(logoPath))
                    row.ConstantItem(80).Image(logoPath).FitArea();

                row.RelativeItem().PaddingLeft(16).Column(c =>
                {
                    c.Item().Text(Setting("company_name", "KETABA POS"))
                        .FontSize(18).Bold().FontColor(Colors.Blue.Darken3);
                    var addr = Setting("company_address");
                    if (!string.IsNullOrEmpty(addr))
                        c.Item().Text(addr).FontSize(10).FontColor(Colors.Grey.Medium);
                    var phone = Setting("company_phone");
                    if (!string.IsNullOrEmpty(phone))
                        c.Item().Text(phone).FontSize(10).FontColor(Colors.Grey.Medium);
                });
            });

            col.Item().PaddingTop(12).LineHorizontal(1).LineColor(Colors.Blue.Medium);
            col.Item().PaddingTop(8).Text("RECEIPT / INVOICE").FontSize(22).Bold().AlignCenter();
            col.Item().PaddingVertical(4).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
        });
    }

    private void ComposePdfContent(IContainer container, Sale sale)
    {
        container.Column(col =>
        {
            col.Item().Row(row =>
            {
                row.RelativeItem().Column(c =>
                {
                    c.Item().Text($"Invoice #: {sale.InvoiceNumber}").SemiBold();
                    c.Item().Text($"Date: {sale.CreatedAt:yyyy-MM-dd HH:mm}");
                    c.Item().Text($"Cashier: {sale.User?.DisplayName ?? "N/A"}");
                });
                row.RelativeItem().Column(c =>
                {
                    c.Item().Text($"Payment: {sale.PaymentMethod}").SemiBold();
                    c.Item().Text($"Customer: {sale.Customer?.Name ?? "Walk-in"}");
                    c.Item().Text($"Status: {sale.Status}");
                });
            });

            col.Item().PaddingVertical(8).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

            col.Item().Table(table =>
            {
                table.ColumnsDefinition(c =>
                {
                    c.RelativeColumn(4);
                    c.ConstantColumn(50);
                    c.ConstantColumn(80);
                    c.ConstantColumn(70);
                    c.ConstantColumn(80);
                });

                table.Header(h =>
                {
                    h.Cell().Background(Colors.Blue.Lighten4)
                        .Padding(6).Text("Item").Bold().FontSize(10);
                    h.Cell().Background(Colors.Blue.Lighten4)
                        .Padding(6).Text("Qty").Bold().FontSize(10).AlignCenter();
                    h.Cell().Background(Colors.Blue.Lighten4)
                        .Padding(6).Text("Price").Bold().FontSize(10).AlignRight();
                    h.Cell().Background(Colors.Blue.Lighten4)
                        .Padding(6).Text("Disc.").Bold().FontSize(10).AlignRight();
                    h.Cell().Background(Colors.Blue.Lighten4)
                        .Padding(6).Text("Total").Bold().FontSize(10).AlignRight();
                });

                var index = 0;
                foreach (var item in sale.SaleItems)
                {
                    var bg = index % 2 == 0 ? Colors.White : Colors.Grey.Lighten4;
                    table.Cell().Background(bg).Padding(6).Text(item.Product?.Name ?? "Item").FontSize(10);
                    table.Cell().Background(bg).Padding(6).Text(item.Quantity.ToString()).FontSize(10).AlignCenter();
                    table.Cell().Background(bg).Padding(6).Text(item.UnitPrice.ToString("N2")).FontSize(10).AlignRight();
                    table.Cell().Background(bg).Padding(6)
                        .Text(item.DiscountAmount > 0 ? item.DiscountAmount.ToString("N2") : "-")
                        .FontSize(10).AlignRight();
                    table.Cell().Background(bg).Padding(6).Text(item.TotalPrice.ToString("N2"))
                        .FontSize(10).AlignRight().Bold();
                    index++;
                }
            });

            col.Item().PaddingVertical(4).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

            col.Item().AlignRight().Width(250).Column(c =>
            {
                AddPdfTotalRow(c, "Subtotal:", sale.Subtotal, false);
                AddPdfTotalRow(c, "Tax:", sale.TaxAmount, false);
                if (sale.DiscountAmount > 0)
                    AddPdfTotalRow(c, "Discount:", -sale.DiscountAmount, false);
                c.Item().PaddingVertical(2).LineHorizontal(1);
                AddPdfTotalRow(c, "TOTAL:", sale.TotalAmount, true);
                AddPdfTotalRow(c, "Paid:", sale.PaidAmount, false);
                AddPdfTotalRow(c, "Change:", sale.ChangeAmount, false);
            });

            var footer = Setting("receipt_footer", "Thank you for your purchase!");
            col.Item().PaddingTop(16).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
            col.Item().PaddingTop(8).Text(footer).FontSize(12).Italic().AlignCenter().FontColor(Colors.Grey.Medium);
        });
    }

    private static void AddPdfTotalRow(ColumnDescriptor c, string label, decimal value, bool bold)
    {
        c.Item().Row(r =>
        {
            r.RelativeItem().Text(label).SemiBold().FontSize(bold ? 14 : 11);
            var cell = r.ConstantItem(80).AlignRight().Text(value.ToString("N2")).FontSize(bold ? 14 : 11);
            if (bold) cell.Bold();
        });
    }
}
